### ISSUE TITLE
No output from `fmt.println` when called from dll loaded by host application

### ISSUE THREAD

**Issue by zacharycarter** [odin-lang/Odin#1301]
## Context

I've been working on a plugin architecture implementation with Odin and noticed that I was unable to produce any output with `core:fmt.println` from within my shared library code. I am able to make `core:libc.printf` work however `fmt.println` won't produce any output given an Odin `string` or a `cstring`.

Whether the proc in the dll is `proc "c"` or  `proc`, doesn't make any difference.

```
Odin: dev-2021-11:600d19c5
OS:   Windows 10 Professional (version: 21H1), build 19043.1288
CPU:  AMD Ryzen 7 2700X Eight-Core Processor
RAM:  32693 MiB
```

## Expected Behavior

Some output is logged

## Current Behavior

No output is logged

### Steps to Reproduce

Compile and run the following example code:
```
package dll

import "core:fmt"

@export
my_lib_foo :: proc() {
    fmt.println("my_lib_foo")
}
```

```
package main

import "core:dynlib"

main :: proc() {
    lib, ok := dynlib.load_library("./mylib.dll");
    assert(ok, "cant load lib");

    ptr, sym_ok := dynlib.symbol_address(lib, "my_lib_foo");
    assert(sym_ok, "could not find symbol");

    fn := cast(proc()) ptr;
    fn();
}
```

The first snippet needs to be compiled as a `dll` and the second an `exe`. Ensure the dll is named `mylib.dll` and is in the same directory as the host application `exe`.

### Failure Logs
- N/A

**Comment by Tetralux** [comment]
I did a little playing around and found a couple of things:

1) `os.stdout` is not set up properly to work in a DLL - but you can do this in the proc, to fix that:
```odin
h := win32.STD_OUTPUT_HANDLE
os.stdout = os.get_std_handle(uint(h))
```

2) In `wprintln`, it turns out that `args[0].id` is a very large number (432345564227567617 in my case), but `type_info_of(args[0].id)` returns a `Type_Info` with an empty `variant`.
This leads me to imagine that the typeinfo for `string` is not correctly set up in a DLL, or that it gets corrupted in a DLL.

**Comment by zacharycarter** [comment]
> I did a little playing around and found a couple of things:
> 
> 1. `os.stdout` is not set up properly to work in a DLL - but you can do this in the proc, to fix that (at least so it works for exploration):
> 
> ```odin
> h := win32.STD_OUTPUT_HANDLE
> os.stdout = os.get_std_handle(uint(h))
> ```
> 
> 1. In `wprintln`, it turns out that `args[0].id` is a very large number (`432345564227567617` (`0x600000000000001`) in my case), but `type_info_of(args[0].id)` returns a `Type_Info` with an empty `variant`.
>    This leads me to imagine that the typeinfo for `string` is not correctly set up in a DLL, or that it gets corrupted in a DLL.

Just to confirm this on my end as well, I'm seeing a value of `1` being computed for the `typeid`, and then being used as an index with the subscript operator on the `type_table` lookup table, in windbg. 

I did a bit more digging as well and it looks like the `id` value sent to `printf` with `d` as the format specifier will produce: `110497856` for a string coming from a `dll` but normally would produce `38551504`.

**Comment by JesseRMeyer** [comment]
If this is a symptom of types being undefined across the DLL boundary, then I propose the following:

- Basic Odin types should be evaluated in a deterministic way such that they are guaranteed to print across shared libraries. That is, their type_id is constant for all Odin programs of a particular compiler version.  (int, string, etc).  This comes at the cost of leading some users into the false impression that println* prints all types across the shared library boundary, so the question is whether this is worth the benefit.

- The family of println functions should print an error if a typeid is not valid for a given input.

**Comment by thePHTest** [comment]
I suspect this is now resolved with today's commit for correct linkage of entry points: https://github.com/odin-lang/Odin/commit/fb0a3ab7c14d4bc3b821cef723ec6ea3e956c956

**Comment by zacharycarter** [comment]
Can confirm this is working with latest Odin. Closing this issue :)

**Comment by ccll** [comment]
The problem still exists while the Odin code is compiled to a static library with `-no-entry-point`, then linked and called from a C executable, can confirm the `os.stdout` hack proposed by @zacharycarter works in this situation.

The fix in https://github.com/odin-lang/Odin/commit/fb0a3ab7c14d4bc3b821cef723ec6ea3e956c956 seems to handle the init in DllMain(), which is only for dynamic linking.

I feel that calling into Odin from C needs a bunch of things to get right, including the `context` pointer init, so I'm wondering if Odin's runtime could provide some **runtime init** function for people to call, which would make it less hacky.
