### ISSUE TITLE
core:sync: semaphores aren't working properly

### ISSUE THREAD

**Issue by ftphikari** [odin-lang/Odin#1647]
Documentation for sync semaphore says:

> When waited upon, blocks until the internal count is greater than zero, then subtracts one.

It does not subtract anything using either `ODIN_SYNC_SEMA_USE_FUTEX` `true` or `false` implementations.

Following piece of code works when `ODIN_SYNC_SEMA_USE_FUTEX` is set to `true`, but is clearly a hack
```odin
sync2.sema_wait(&sema)
sync2.sema_post(&sema, -1)
```
When `ODIN_SYNC_SEMA_USE_FUTEX` is set to `false`, this code results in a runtime error, because it tries to decrement wait_group counter from 0 to -1.

**Comment by gingerBill** [comment]
Should be fixed now in the latest commit.

**Comment by ftphikari** [comment]
@gingerBill set ODIN_SYNC_SEMA_USE_FUTEX to false and it still does not work properly
