### ISSUE TITLE
Debug info tracking

### ISSUE THREAD

**Issue by JesseRMeyer** [odin-lang/Odin#1858]
```go
main :: proc() {

    bob := 0
    for i := 0; i < 10; i += 1 {
        bob += i
    }

    i := 0 //comment this out to 'fix' debug info
```

`i` will always report 0 unless the second `i` is commented out, and then correctly reports its value.

If this logic is hoisted into its own function, `i` simply reports nonsense values, even after the second `i` is overwritten, implying the possibility of reporting an incorrect stack location.

`odin build debug_example -o:minimal -debug`

```
        Odin: dev-2022-06
        OS:   Windows 10 Home Basic (version: 21H2), build 19044.1766
        CPU:  Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
        RAM:  32717 MiB
```

**Comment by gingerBill** [comment]
This should be fixed now.

**Comment by JesseRMeyer** [comment]
As mentioned in the other PR, variable state tracking has improved but the problem is not fixed in its entirety.
![bob](https://user-images.githubusercontent.com/5846309/179520179-c5d0a329-17b1-4a49-bbf4-8d449768187d.JPG)

Try playing with the provided code to get a feel for the variable tracking weirdness.  If `i := 0 //comment this out to 'fix' debug info` is commented out, then `i` in the loop goes out of tracking scope on the condition check (is that intended?).  If it not commented out, `i`i is not out of scope, but reports uninitialized values.  

Visual Studio's debug view makes this a little clearer.
![ms_bob](https://user-images.githubusercontent.com/5846309/179520800-9598c688-4fb6-4976-a6b7-2b6ec691ead7.JPG)

**Comment by fabiansperber** [comment]
That is (kind of) expected. The initialization will only happen once you step over that line, so when stepping the first time on the `for` line, it should change from uninitialized to 0 (next breakpoint on that line is before checking the condition).

We could have an(the) extra zero-initialization step (A) happen before the debug breakpoint, but in the long term, imo, there should not be an initialization step except the one that assigns the value being used (`0` here).
For example `for i:=slow_function(); i< 10; i += 1 {` we would want the function call to not yet have happened when a breakpoint is triggered on the `for`, so there would be no value to assign to `i`.

But that is just defining expectations, can make it work either way.

(A) Right now, there are two stores writing 0 because zero-initialization is always done for variables, regardless if there is a value assigned in the declaration. My guess is that this was only a workaround for some other issue and not the intended way for variable initialization to work.

**Comment by JesseRMeyer** [comment]
Hovering over `bob` when the breakpoint is set to line 2463 simply doesn't reveal any information at all, because `bob` isn't alive yet.  That was my expectation for `i` when first stepping into the `for` loop -- only see debug values when the variable's lifetime is active.  Devil in the details, and there are lots of details, so this may not be feasible.

But more broadly, there, I think, undeniably remains the scoping issue wrt the second `i`.

**Comment by JesseRMeyer** [comment]
Not stale.  Is there another means to tell Github issues are not stale without spamming the discussion?
