### ISSUE TITLE
Struct containing a maybe of the same type leads to hung compilation

### ISSUE THREAD

**Issue by Bambo-Borris** [odin-lang/Odin#4504]
## Context
Whilst implementing something in a project I noticed that the below snippet of code would not generate a compilation error, but would instead leave the build in a hung state. The code itself (from my perspective) is nonsensical and I only discovered the issue when the build hung after mistakenly providing the same type to a struct field of type `Maybe` where the `Maybe` wraps the same type as the struct it's within.

```odin
package test

Test :: struct {
	t: Maybe(Test),
}

main :: proc() {}
```

```
Odin:    dev-2024-11:e6475fec4
OS:      Windows 11 Home Basic (version: 23H2), build 22631.4460
CPU:     12th Gen Intel(R) Core(TM) i7-12700KF
RAM:     32487 MiB
Backend: LLVM 18.1.8
```

## Expected Behavior

Compilation failure similar to if you attempt to:
```
Error: Illegal declaration cycle of `Test`
```
## Current Behavior

Compilation hangs and will not halt unless the user forces it to.

**Comment by Kelimion** [comment]
Might be related to #4498.

**Comment by gingerBill** [comment]
Fixed in https://github.com/odin-lang/Odin/commit/9115c7aa1395f8be2c583a28a6be6a5542704169

**Comment by Bambo-Borris** [comment]
I'll give this a test locally and confirm.

**Comment by Bambo-Borris** [comment]
Seems like the issue is resolved, I now get a compiler error and the failing to halt issue is gone.

**Comment by gingerBill** [comment]
So it's not fixed because it's now a race condition. Which is "better"?

**Comment by Kelimion** [comment]
> So it's not fixed because it's now a race condition. Which is "better"?

The hanging compile may ironically be better because it's consistent.
